# Site settings
title: Todd Zimmerman	
email: zimmermant@ustout.edu 
description: > # this means to ignore newlines until "baseurl:"
     Prof. Todd Zimmerman
     University of Wisconsin - Stout
     Posted work is licensed under a Creative Commons BY-NC-SA 4.0 License unless noted otherwise.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zimmermant.github.io" # the base hostname & protocol for your site
# twitter_username: twitternamehere
github_username:  zimmermant	

# Build settings
markdown: kramdown
